insert into C_VENTAS
select 
S.NOMBRE
,V.FECHA
,V.ORIGEN
,V.DOCTO
,V.IMPORTE
,V.IMPUESTO
,V.TOTAL
,V.CLIENTE_ID
,V.NOMBRE
,V.SUCURSAL_ID
,V.COMENTARIO
,V.CARGO_ID,NOW()
from SX_VENTAS V JOIN SW_SUCURSALES S ON(S.SUCURSAL_ID=V.SUCURSAL_ID) 
WHERE V.FECHA=?
