SELECT TO_NUMBER(TO_CHAR(FECHA,'MM')) AS MES,
SUM(PRECIOLISTA*-CANTIDAD) AS VENTAS_PL
,SUM(PRECIOLISTA*-CANTIDAD)-SUM(PRECIOFACTURADO*-CANTIDAD) AS DESCUENTO_AF
,SUM(PRECIOFACTURADO*-CANTIDAD) AS VENTAS_PF
,SUM(DESCUENTO_CONTADO*(PRECIOFACTURADO*-CANTIDAD)/100) AS DESCUENTO_F
,SUM( (PRECIOFACTURADO*-CANTIDAD)-(DESCUENTO_CONTADO*(PRECIOFACTURADO*-CANTIDAD)/100)) AS VENTA_SN
,SUM(IMP_PROVISION) AS PROVISION
,SUM( (PRECIOFACTURADO*-CANTIDAD)*DESCUENTO_C/100) AS DESCUENTO_NC
,SUM( (PRECIOFACTURADO*-CANTIDAD)*PORC_DEVO/100) AS DEVOLUCIONES
,SUM( (PRECIOFACTURADO*-CANTIDAD)-(DESCUENTO_CONTADO*(PRECIOFACTURADO*-CANTIDAD)/100)) 
    -SUM(IMP_PROVISION) 
    -SUM( (PRECIOFACTURADO*-CANTIDAD)*DESCUENTO_C/100) 
    -SUM( (PRECIOFACTURADO*-CANTIDAD)*PORC_DEVO/100) AS VENTA_NETA
,SUM( (-CANTIDAD-DEVOLUCIONES)*COSTO) AS COSTO
,SUM(F_CRT_MO) AS SERVICIO
FROM VENTASDET_2008 WHERE MES BETWEEN 1 AND 9
GROUP BY TO_NUMBER(TO_CHAR(FECHA,'MM'))
