SELECT X.VENTA_ID,X.DESCUENTO FROM SW_VENTASCREDITO X 
JOIN SW_VENTAS B ON( X.VENTA_ID=B.VENTA_ID)
WHERE  B.TIPO IN('E','S')  AND B.FECHA BETWEEN ? AND ?
AND X.VENTA_ID NOT IN((SELECT XX.VENTA_ID FROM SW_NOTASDET XX 
		WHERE XX.TIPO IN('U','L') 
		AND XX.VENTA_ID=B.VENTA_ID AND XX.FECHA<=?))