package com.luxsoft.sw3.tesoreria.model;

public enum Clasificacion {
	RETIRO
	,COMISION		
	,IMPUESTO_POR_TRASPASO
	,DEPOSITO
	,INTERESES
	,IMPUESTO_POR_INTERESES
	,IVA_COMISION_BANCARIA
	,DEPOSITO_POR_INVERSION
	,RETIRO_POR_INVERSION
	
}