SELECT A.* FROM (
select 'LINEA' AS TIPO,L.LINEA_ID AS ID,L.NOMBRE,L.CORTE_ID,T.PRECIO_CONTADO,T.PRECIO_CREDITO,t.maximo_hojas,M.MEDIDA_ID,M.LONG_MIN,M.LONG_MAX,M.CORTES
,P.PRODUCTO_ID,P.CLAVE,P.DESCRIPCION,P.ancho,P.largo,P.KILOS,P.GRAMOS,P.calibre,P.caras,P.PRESENTACION,P.deLinea,P.nacional
from sx_productos p 
join sx_lineas l on(l.LINEA_ID=p.LINEA_ID)
JOIN sx_cortes T ON(T.CORTE_ID=L.CORTE_ID)
JOIN sx_cortes_medidas M ON(M.CORTE_ID=T.CORTE_ID)
where p.clave=@PRODUCTO AND @MEDIDA BETWEEN M.LONG_MIN AND M.LONG_MAX
UNION
select 'CLASE' AS TIPO,C.CLASE_ID AS ID,C.NOMBRE,C.CORTE_ID,T.PRECIO_CONTADO,T.PRECIO_CREDITO,t.maximo_hojas,M.MEDIDA_ID,M.LONG_MIN,M.LONG_MAX,M.CORTES
,P.PRODUCTO_ID,P.CLAVE,P.DESCRIPCION,P.ancho,P.largo,P.KILOS,P.GRAMOS,P.calibre,P.caras,P.PRESENTACION,P.deLinea,P.nacional
from sx_productos p 
join sx_clases c on(c.CLASE_ID=p.clase_ID)
JOIN sx_cortes T ON(T.CORTE_ID=C.CORTE_ID)
JOIN sx_cortes_medidas M ON(M.CORTE_ID=T.CORTE_ID)
where p.clave=@PRODUCTO AND @MEDIDA BETWEEN M.LONG_MIN AND M.LONG_MAX
) A
ORDER BY TIPO ASC