
select SUBSTR(CLAVE,1,1) AS INI ,SUBSTR(CLAVE,2,2) AS SUC ,MAX(SUBSTR(CLAVE,4,4)) AS SEC 
,CONCAT(SUBSTR(CLAVE,1,1),SUBSTR(CLAVE,2,2),SUBSTR((10000+MAX(SUBSTR(CLAVE,4,4))+1),2,4)) AS NUEVO 
from SX_clientes where SUBSTR(CLAVE,1,1)='Q' AND SUBSTR(CLAVE,2,2)=03  
GROUP BY SUBSTR(CLAVE,1,1) ,SUBSTR(CLAVE,2,2) 