select 'WIN' AS ORIGEN,S.NOMBRE AS SUCURSAL,a.FOLIO,'' AS SOLICITO,A.FECHA,A.CLAVE,A.NOMBRE,A.ORIGEN AS TIPO_VTA,A.SIIPAP_ID,A.FECHA_DEPOSITO,A.REFERENCIA
,CASE WHEN A.TRANSFERENCIA>0 THEN 'T' 
      WHEN A.EFECTIVO>0 AND A.CHEQUE>0 THEN 'M'
      WHEN A.EFECTIVO>0 AND A.CHEQUE=0 THEN 'E'
      WHEN A.EFECTIVO=0 AND A.CHEQUE>0 THEN 'H' ELSE 'X' END AS FPAGO
,(SELECT X.NOMBRE_SIIPAP FROM SW_BANCOS X WHERE X.NOMBRE=a.BANCO) AS BANCO,a.TOTAL
,(SELECT B.NOMBRE_SIIPAP FROM SW_CUENTAS X JOIN SW_BANCOS B ON(B.BANCO_ID=X.BANCO_ID) WHERE   A.CUENTA_ID=X.id) AS BANCO_DEST
,CASE  WHEN A.SALVO_COBRO IS TRUE AND A.AUTORIZACION_ID IS NULL THEN 'SBC'
        WHEN A.AUTORIZACION_ID IS NOT NULL THEN 'OK' 
        ELSE 'PEN' END AS STATUS       
,A.COMENTARIO
 from sx_cxc_abonos A
JOIN sw_sucursales S ON(S.SUCURSAL_ID=A.SUCURSAL_ID)
where tipo_id='PAGO_DEP' AND fecha BETWEEN '2009/12/01' AND '2009/12/31'  
AND COMENTARIO IS NOT NULL AND COMENTARIO NOT LIKE 'CANCELADO%'