SELECT (SELECT XX.NOMBRE FROM SX_PROVEEDORES XX WHERE XX.PROVEEDOR_ID=P.PROVEEDOR_ID) AS PROVEEDOR 
,ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166 AS MESES_POR_PERIODO
,L.NOMBRE AS LINEA,C.NOMBRE AS CLASE,M.NOMBRE AS MARCA
,p.CLAVE,p.DESCRIPCION AS DESCRIPCION,P.ANCHO,P.LARGO,P.GRAMOS,P.KILOS,P.DELINEA
,ROUND(SUM(EXI),3) AS EXISTENCIA
,ROUND(SUM(VTA+DEV),1) AS VENTAS
,ROUND(ROUND(SUM(VTA+DEV),1)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166),1) AS PROMEDIO_VTA
,ROUND(IFNULL(IFNULL(ROUND(SUM(EXI),3),0)/IFNULL(ROUND(ROUND(SUM(VTA+DEV),1)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166),1),0),0),1) AS ALCANCE_INV
,SUM(PED) AS PEDIDOS_SOLICITADOS
,SUM(DEP) AS DEPURADO
,SUM(ADU) AS ADUANA
,SUM(ENT) AS ENTRADA
,ROUND(SUM(PEND),3) AS PEDIDOS_PENDIENTES  
,ROUND(  IFNULL(IFNULL(SUM(PEND),0)/IFNULL(SUM(VTA+DEV)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166),0),0) ,1) AS ALCANCE_PED
,SUM(EXI)*P.KILOS/1000 AS EXISTENCIA_TON
,(SUM(VTA+DEV)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166))*P.KILOS/1000 AS PROMEDIO_VTA_TON
,SUM(PEND)*P.KILOS/1000 AS PEDIDOS_PEND_TON
FROM (
SELECT X.PRODUCTO_ID,X.CLAVE,SUM(X.CANTIDAD/X.FACTORU) AS EXI,0 AS VTA,0 AS DEV,0 AS PED,0 AS DEP,0 AS ADU,0 AS ENT,0 AS PEND FROM SX_EXISTENCIAS X WHERE X.YEAR=YEAR(@FECHA_FIN) AND  X.MES=MONTH(@FECHA_FIN) AND  X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
SELECT X.PRODUCTO_ID,X.CLAVE,0,SUM(-X.CANTIDAD/X.FACTORU),0,0,0,0,0,0 FROM SX_VENTASDET X WHERE X.FECHA BETWEEN @FECHA_INI AND  @FECHA_FIN AND X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
SELECT X.PRODUCTO_ID,X.CLAVE,0,0,SUM(-X.CANTIDAD/X.FACTORU),0,0,0,0,0 FROM sx_inventario_dev X WHERE X.FECHA BETWEEN @FECHA_INI AND  @FECHA_FIN AND X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,SUM(X.SOLICITADO/X.FACTOR) AS PED,0,0,0,0
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,0,SUM(X.DEPURADO/X.FACTOR) AS DEP,0,0,0
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,0,0,SUM(X.ADUANA/X.FACTOR) AS ADU,0,0
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,0,0,0,IFNULL(SUM((SELECT SUM(I.CANTIDAD/I.FACTORU) FROM sx_inventario_com I WHERE I.COMPRADET_ID=X.COMPRADET_ID)),0) AS ENT,0
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,0,0,0,0,SUM(((X.SOLICITADO-X.DEPURADO-X.ADUANA)/X.FACTOR)-IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU) FROM sx_inventario_com I WHERE I.COMPRADET_ID=X.COMPRADET_ID),0)) AS PENDTE
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
) AS A
JOIN sx_productos P ON(A.PRODUCTO_ID=P.PRODUCTO_ID)
join sx_LINEAS L on(L.LINEA_ID=p.LINEA_ID)
JOIN SX_CLASES C ON(C.CLASE_ID=P.CLASE_ID)
JOIN sx_marcas M ON(M.MARCA_ID=P.MARCA_ID)
WHERE P.ACTIVO IS TRUE AND P.INVENTARIABLE IS TRUE  
AND P.PRODUCTO_ID IN(SELECT X.PRODUCTO_ID FROM sx_proveedor_productos X WHERE X.PRODUCTO_ID=P.PRODUCTO_ID AND X.PROVEEDOR_ID IN(42,60))  
GROUP BY A.CLAVE,A.PRODUCTO_ID