SELECT ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166 AS MESES_POR_PERIODO
,(SELECT X.NOMBRE FROM SX_PROVEEDORES X WHERE X.PROVEEDOR_ID=P.PROVEEDOR_ID) AS PROVEEDOR
,L.NOMBRE AS LINEA
,C.NOMBRE AS CLASE
,M.NOMBRE AS MARCA
,p.CLAVE AS CLAVE
,p.DELINEA
,p.DESCRIPCION AS DESCRIPCION 
,P.KILOS AS KILOS 
,ROUND(SUM(EXI),3) AS EXISTENCIA
,ROUND(SUM(VTA+DEV),1) AS VENTAS
,ROUND(ROUND(SUM(VTA+DEV),1)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166),1) AS PROMEDIO_VTA
,ROUND(IFNULL(IFNULL(ROUND(SUM(EXI),3),0)/IFNULL(ROUND(ROUND(SUM(VTA+DEV),1)/(ROUND((ROUND(TO_DAYS(@FECHA_FIN)-TO_DAYS(@FECHA_INI),0)),0)/30.4166),1),0),0),1) AS ALCANCE_TOTAL
,ROUND(SUM(PEND),3) AS PEDIDOS_PENDIENTES  
FROM (
SELECT X.PRODUCTO_ID,X.CLAVE,SUM(X.CANTIDAD/X.FACTORU) AS EXI,0 AS VTA,0 AS DEV,0 AS PEND FROM SX_EXISTENCIAS X WHERE X.YEAR=YEAR(@FECHA_FIN) AND  X.MES=MONTH(@FECHA_FIN) AND  @EXI_SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
SELECT X.PRODUCTO_ID,X.CLAVE,0,SUM(-X.CANTIDAD/X.FACTORU),0,0 FROM SX_VENTASDET X WHERE X.FECHA BETWEEN @FECHA_INI AND  @FECHA_FIN AND X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
SELECT X.PRODUCTO_ID,X.CLAVE,0,0,SUM(-X.CANTIDAD/X.FACTORU),0 FROM sx_inventario_dev X WHERE X.FECHA BETWEEN @FECHA_INI AND  @FECHA_FIN AND X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
UNION
select X.PRODUCTO_ID,X.CLAVE,0,0,0,SUM(((X.SOLICITADO-X.DEPURADO)/X.FACTOR)-IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU) FROM sx_inventario_com I WHERE I.COMPRADET_ID=X.COMPRADET_ID),0)) AS PENDTE
from sx_compras2_det X WHERE X.SUCURSAL_ID LIKE @SUCURSAL_ID GROUP BY X.CLAVE,X.PRODUCTO_ID
) AS A
JOIN sx_productos P ON(A.PRODUCTO_ID=P.PRODUCTO_ID)
join sx_LINEAS L on(L.LINEA_ID=p.LINEA_ID)
JOIN SX_CLASES C ON(C.CLASE_ID=P.CLASE_ID)
JOIN sx_marcas M ON(M.MARCA_ID=P.MARCA_ID)
WHERE P.ACTIVO IS TRUE AND P.INVENTARIABLE IS TRUE 
GROUP BY A.CLAVE,A.PRODUCTO_ID