SELECT A.ALMACEN_ID,(CURRENT_DATE) AS  FECHA ,O.PRODUCTO_DESTINO_ID,YEAR(CURRENT_DATE) AS YEAR,MONTH(CURRENT_DATE) AS MES,O.DESTINO_CLAVE AS CLAVE,O.DESTINO_DESCRIPCION AS DESCRIPCION
,SUM((IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=CURRENT_DATE),0))/1000) AS CANTIDAD
,P.UNIDAD,P.NACIONAL,P.KILOS,(SELECT FACTOR FROM sx_unidades U WHERE U.UNIDAD=P.UNIDAD) AS FACTORU,((E.PRECIO_M2* R.METROS2)/ R.ENTRADA)*1000 AS COSTO,0 AS COSTOP,0 AS COSTOU
FROM sx_maq_recepcion_cortedet R 	
JOIN sx_maq_entradasdet E ON (R.ENTRADADET_ID=E.ENTRADADET_ID )
JOIN sx_almacenes A ON(A.ALMACEN_ID=R.ALMACEN_ID) 
JOIN sx_maq_ordenesdet O ON(O.ORDENDET_ID=R.ORDENDET_ID)
JOIN sx_productos P ON (P.PRODUCTO_ID=O.PRODUCTO_DESTINO_ID)
WHERE DATE(R.FECHA)<=CURRENT_DATE AND A.ALMACEN_ID LIKE '%' AND 
(R.ENTRADA-IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=CURRENT_DATE),0))>0	
GROUP BY A.ALMACEN_ID,O.DESTINO_CLAVE
UNION
SELECT A.ALMACEN_ID,(CURRENT_DATE) AS  FECHA ,D.PRODUCTO_ID,YEAR(CURRENT_DATE) AS YEAR,MONTH(CURRENT_DATE) AS MES,D.CLAVE,D.DESCRIPCION
,SUM(D.KILOS-IFNULL((SELECT SUM(O.KILOS) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(O.FECHA)<=CURRENT_DATE),0) 
    -IFNULL((SELECT SUM(S.CANTIDAD) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=CURRENT_DATE),0)) AS CANTIDAD
,P.UNIDAD,P.NACIONAL,P.KILOS,(SELECT FACTOR FROM sx_unidades U WHERE U.UNIDAD=P.UNIDAD) AS FACTORU
,D.PRECIO_KILO AS COSTO,0 AS COSTOP,0 AS COSTOU
FROM sx_maq_entradasdet D JOIN sx_almacenes A ON(D.ALMACEN_ID=A.ALMACEN_ID) JOIN sx_productos P ON(P.PRODUCTO_ID=D.PRODUCTO_ID)
WHERE D.FECHA<=CURRENT_DATE AND D.ALMACEN_ID like '%' and 
(D.METROS2 -IFNULL((SELECT SUM(O.METROS2) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID AND DATE(O.FECHA)<=CURRENT_DATE ),0)
   -IFNULL((SELECT SUM(S.CANTIDAD*D.METROS2/D.KILOS) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=CURRENT_DATE),0) )<>0
GROUP BY A.ALMACEN_ID,D.CLAVE