
SELECT IFNULL(V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0),0) AS SALDO
FROM sx_ventas V WHERE  V.CLAVE=?  AND 
IFNULL(V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0),0)<>0
AND V.CARGO_ID  IN(SELECT X.CARGO_ID FROM sx_juridico X WHERE X.CARGO_ID=V.CARGO_ID)   
GROUP BY V.CLAVE