SELECT IFNULL(V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0),0) AS SALDO
FROM sx_ventas V JOIN SX_CLIENTES C ON(C.CLAVE=V.CLAVE) 
WHERE DATE(V.FECHA) > '2008/12/31' AND V.ORIGEN='CHE'  AND V.CLAVE=?  
AND IFNULL(V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0),0)<>0
AND V.CARGO_ID NOT IN(SELECT X.CARGO_ID FROM sx_juridico X)   
GROUP BY V.CLAVE