SELECT IFNULL(MAX(ROUND(TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO),0)),0) AS ATRASO
FROM sx_ventas V JOIN SX_CLIENTES_CREDITO C ON(C.CLAVE=V.CLAVE) 
WHERE DATE(V.FECHA) > '2008/12/31' AND V.ORIGEN='CRE'  AND V.CLAVE=?  
AND V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0)<>0
AND V.CARGO_ID NOT IN(SELECT X.CARGO_ID FROM sx_juridico X)   
GROUP BY V.CLAVE