SELECT V.CARGO_ID,V.TIPO,V.DOCTO,V.NFISCAL,V.post_fechado as POSTF,V.FECHA,V.VTO,V.REPROGRAMAR_PAGO AS "REP.PAGO"
,CASE WHEN ROUND(TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO),0) <0 THEN 0 ELSE ROUND(TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO),0) END AS ATR
,S.CLAVE AS SUC,V.CLAVE AS CLIENTE,V.NOMBRE,V.TOTAL
,ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='NOTA' AND ABN_DESCRIPCION LIKE 'DEV%'),0) as DEVS
,ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='NOTA' AND ABN_DESCRIPCION LIKE 'BON%'),0) as BONIFIC
,ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='NOTA' AND ABN_DESCRIPCION LIKE 'DES%'),0) as DESCTOS
/*--CONDICIONADO A LA FACTURA QUE TENGA DESCUENTO O BONIFICACION = 0
,CASE WHEN ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='NOTA' AND ABN_DESCRIPCION LIKE 'BON%'),0)+
      ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='NOTA' AND ABN_DESCRIPCION LIKE 'DES%'),0)<>0 THEN
      0 ELSE V.DESCUENTO END AS "DESC(NOTA)" 
*/
---ESTA COLUMNA YA NO SE USA "NO HAY DESCTOS EN VENTA" SOLO DESCTOS BONIFICADOS
--,V.DESCUENTO AS "DESC(NOTA)"
,ifnull((select sum(X.importe) FROM sx_cxc_aplicaciones x where x.CARGO_ID=v.CARGO_ID AND X.TIPO='PAGO'),0) as PAGOS
,V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0) AS SALDO 
,ifnull((select sum(X.importe) FROM sx_notadecargo_det x where x.VENTA_ID=v.CARGO_ID),0) as "CAR(APLIC)"
,CASE WHEN TRUNCATE((TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO))/7,0)<=0 THEN 0 ELSE TRUNCATE((TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO))/7,0) END AS "CAR(%)"
,(CASE WHEN TRUNCATE((TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO))/7,0)<=0 THEN 0 ELSE TRUNCATE((TO_DAYS(CURRENT_DATE)-TO_DAYS(V.VTO))/7,0) END)
*(V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID AND B.TIPO='NOTA' AND B.ABN_DESCRIPCION LIKE 'DEV%'),0))/100 AS "CAR($)"
,0 AS DF
FROM sx_ventas V 
JOIN SX_CLIENTES_CREDITO C ON(C.CLAVE=V.CLAVE)
JOIN sw_sucursales S ON(V.SUCURSAL_ID=S.SUCURSAL_ID)
WHERE V.FECHA>'2008/12/31' AND V.CLAVE LIKE '%' AND V.ORIGEN='CRE' AND
V.TOTAL-IFNULL((SELECT SUM(B.IMPORTE) FROM sx_cxc_aplicaciones B WHERE B.CARGO_ID=V.CARGO_ID),0)<>0
AND V.CARGO_ID NOT IN(SELECT X.CARGO_ID FROM sx_juridico X)