SELECT A.PRODUCTO_ID,A.CLAVE,SUM(CANTIDAD),
CASE WHEN MONTH(A.FECHA)-1=0 THEN 12 ELSE MONTH(A.FECHA)-1 END AS MES_INI
,CASE WHEN MONTH(A.FECHA)-1=0 THEN YEAR(A.FECHA)-1 ELSE YEAR(A.FECHA) END AS YEAR_INI
,(SELECT E.CANTIDAD FROM SX_EXISTENCIAS E WHERE E.CLAVE=A.CLAVE AND S.SUCURSAL_ID=E.SUCURSAL_ID AND E.MES=(CASE WHEN MONTH(A.FECHA)-1=0 THEN 12 ELSE MONTH(A.FECHA)-1 END) 
AND E.YEAR=(CASE WHEN MONTH(A.FECHA)-1=0 THEN YEAR(A.FECHA)-1 ELSE YEAR(A.FECHA) END)) AS SALDO_INI
,(SELECT E.CANTIDAD FROM sx_existencias E WHERE  E.CLAVE=A.CLAVE AND E.SUCURSAL_ID=S.SUCURSAL_ID AND E.MES = MONTH(A.FECHA) AND E.YEAR=YEAR(A.FECHA)) AS SALDO_FIN
, MES,YEAR(A.FECHA) AS YEAR,S.CLAVE AS SUC,S.NOMBRE AS SUCURSAL, A.CLAVE,A.DESCRIPCION,A.UNIDAD,A.TIPO,A.DOCUMENTO,A.RENGLON,A.FECHA1,A.FECHA,A.CANTIDAD,A.KILOS ,A.COMENTARIO
,SUM(CANTIDAD)
+(SELECT E.CANTIDAD FROM SX_EXISTENCIAS E WHERE E.CLAVE=A.CLAVE AND S.SUCURSAL_ID=E.SUCURSAL_ID AND E.MES=(CASE WHEN MONTH(A.FECHA)-1=0 THEN 12 ELSE MONTH(A.FECHA)-1 END) 
AND E.YEAR=(CASE WHEN MONTH(A.FECHA)-1=0 THEN YEAR(A.FECHA)-1 ELSE YEAR(A.FECHA) END))
-  (SELECT E.CANTIDAD FROM sx_existencias E WHERE  E.CLAVE=A.CLAVE AND E.SUCURSAL_ID=S.SUCURSAL_ID AND E.MES = MONTH(A.FECHA) AND E.YEAR=YEAR(A.FECHA)) AS 'DISCREPANCIA'
FROM 
(
select   0 AS GP, '' AS ORIGEN,i.inventario_id, 'COMPRAS' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,'COM' AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,(SELECT X.COMENTARIO FROM sx_entrada_compras X WHERE X.ID=I.RECEPCION_ID) AS COMENTARIO
from sx_inventario_com  I  WHERE year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
Union
select 0 AS GP, '' AS ORIGEN,i.inventario_id, 'COMPRAS' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,I.MAQUILA_TIPO AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL AS NACIONAL,I.COMENTARIO from sx_inventario_maq  I  WHERE    year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select 0 AS GP,(SELECT X.ORIGEN FROM SX_VENTAS X WHERE X.CARGO_ID=I.VENTA_ID) AS ORIGEN,i.inventario_id, 'VENTAS' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,'FAC' AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE AS CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.CORTES_INSTRUCCION AS COMENTARIO  
from sx_ventasdet  I  WHERE   year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select 0 AS GP, '' AS ORIGEN,i.inventario_id,'VENTAS' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,'DEV' AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,(SELECT X.COMENTARIO FROM SX_DEVOLUCIONES X WHERE X.DEVO_ID=I.DEVO_ID)AS COMENTARIO 
from sx_inventario_dev  I  WHERE   year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select  0 AS GP, '' AS ORIGEN,i.inventario_id, 'MOVIMIENTOS' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,I.CONCEPTO AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.COMENTARIO from sx_inventario_mov  I  WHERE   year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select 0 AS GP, '' AS ORIGEN,i.inventario_id, 'TRANSFORMACION' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,TRTIP AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.COMENTARIO from sx_inventario_trs  I  WHERE   year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select  0 AS GP, '' AS ORIGEN,i.inventario_id, 'TRASLADO' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,CASE WHEN I.CANTIDAD<0 THEN 'TPS' ELSE 'TPE' END AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS
,I.COSTO,I.COSTOP,0 AS GASTOS,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.COMENTARIO from sx_inventario_trd  I  WHERE  year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
UNION
select 0 AS GP, '' AS ORIGEN,i.inventario_id, 'DEV_PROV' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,'DEC' AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.COMENTARIO from sx_inventario_DEC  I  WHERE year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
union
select 0 AS GP, '' AS ORIGEN,i.inventario_id, 'TRANSFORMACION' AS GRUPO,I.FECHA as FECHA1,I.FECHA AS FECHA,'KIT' AS TIPO,I.DOCUMENTO,I.RENGLON,I.SUCURSAL_ID,I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION,I.UNIDAD_ID AS UNIDAD,I.FACTORU,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.NACIONAL,I.COMENTARIO from sx_inventario_kit  I  WHERE  year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
UNION
SELECT 0 AS GP,'EXI' AS ORIGEN, inventario_id, '' AS GRUPO,I.FECHA AS FECHA1,concat(YEAR(I.FECHA),'/',MONTH(I.FECHA),'/',DAY(I.FECHA),' 23:58:46.0') AS FECHA,'' AS TIPO,0 DOCUMENTO,0 RENGLON, I.SUCURSAL_ID, I.PRODUCTO_ID,I.CLAVE,I.DESCRIPCION, 0  AS UNIDAD,I.FACTORU, 0 CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,0 AS GASTOS
,I.YEAR,I.MES,I.NACIONAL,'' COMENTARIO  FROM   SX_EXISTENCIAS  I  WHERE   year(I.FECHA) ='@YEAR' AND month(I.FECHA)='@MES'
) AS A JOIN SW_SUCURSALES S ON (S.SUCURSAL_ID=A.SUCURSAL_ID) JOIN sx_productos P ON (P.PRODUCTO_ID=A.PRODUCTO_ID)
WHERE P.INVENTARIABLE IS TRUE AND  
S.SUCURSAL_ID='@SUCURSAL' AND 
 year(A.FECHA) ='@YEAR'  AND MONTH(A.FECHA)='@MES' 
GROUP BY 
PRODUCTO_ID
HAVING
(ROUND(SUM(CANTIDAD),3)
+ROUND((SELECT E.CANTIDAD FROM SX_EXISTENCIAS E WHERE E.CLAVE=A.CLAVE AND E.SUCURSAL_ID='@SUCURSAL' AND E.MES=(CASE WHEN MONTH(A.FECHA)-1=0 THEN 12 ELSE MONTH(A.FECHA)-1 END) 
AND E.YEAR=(CASE WHEN MONTH(A.FECHA)-1=0 THEN YEAR(A.FECHA)-1 ELSE YEAR(A.FECHA) END)),3)
-  ROUND((SELECT E.CANTIDAD FROM sx_existencias E WHERE  E.CLAVE=A.CLAVE AND E.SUCURSAL_ID='@SUCURSAL' AND E.MES = MONTH(A.FECHA) AND E.YEAR=YEAR(A.FECHA)),3)) <>0
ORDER BY 
A.FECHA