
ALTER TABLE SX_LP_CLIENTE COLUMN LISTA_ID BIGINT(20) NOT NULL;

ALTER TABLE SX_LP_CLIENTE_DET MODIFY COLUMN LISTADET_ID BIGINT(20) NOT NULL;


INSERT INTO sx_table_ids (GEN_KEY,GEN_VALUE) VALUES ('LP_CLIENTES_ID',50);

INSERT INTO sx_table_ids (GEN_KEY,GEN_VALUE) VALUES ('LP_CLIENTES_DET_ID',2000);