
DROP TRIGGER LP_PROVS_BEF_INS

DROP TRIGGER LP_PROVS_BEF_UPD

ALTER TABLE sx_lp_provs MODIFY COLUMN id BIGINT(20) NOT NULL;

ALTER TABLE sx_lp_provs_det MODIFY COLUMN LISTADET_ID BIGINT(20) NOT NULL;

alter table sx_lp_provs add column TX_IMPORTADO datetime;

alter table sx_lp_provs add column TX_REPLICADO datetime;

INSERT INTO sx_table_ids (GEN_KEY,GEN_VALUE) VALUES ('LP_PROVEEDORES_ID',500);

INSERT INTO sx_table_ids (GEN_KEY,GEN_VALUE) VALUES ('LP_PROVEEDORES_DET_ID',15000);