select 'Inventario Movs(AJU,CIM,MER,RMC,OIM)' AS DESCRIPCION,CASE WHEN I.CANTIDAD<0 THEN '151654' ELSE 'OING01' END AS CONCEPTO
,I.SUCURSAL_ID,SUM(ROUND(I.CANTIDAD/I.FACTORU*I.COSTOP,2)) as COSTO from sx_inventario_mov I  join sx_productos p on(p.producto_id=i.producto_id) 
where I.CONCEPTO IN('AJU','CIM','MER','RMC','OIM') AND p.inventariable is true and I.FECHA 
BETWEEN '@FECHA_INI 00:00:00' AND '@FECHA_FIN 23:59:59' group by I.SUCURSAL_ID,CASE WHEN I.CANTIDAD<0 THEN 'NO DEDUCIBLE' ELSE 'PRODUCTO' END 
UNION
select 'Inventario Transformaciones' AS TIPO,CASE WHEN SUM(CASE WHEN I.CANTIDAD>0 THEN (I.CANTIDAD/I.FACTORU*I.COSTOORIGEN) ELSE (I.CANTIDAD/I.FACTORU*I.COSTOP) END)<0 THEN 'OGST01' ELSE 'OING01' END AS CONCEPTO,I.SUCURSAL_ID
,SUM(CASE WHEN I.CANTIDAD>0 THEN ROUND((I.CANTIDAD/I.FACTORU*I.COSTOORIGEN),2) ELSE ROUND((I.CANTIDAD/I.FACTORU*I.COSTOP),2) END) as COSTO
from sx_inventario_trs I  join sx_productos p on(p.producto_id=i.producto_id) where p.inventariable is true  
and I.FECHA BETWEEN '@FECHA_INI 00:00:00' AND '@FECHA_FIN 23:59:59' group by I.SUCURSAL_ID
union
select 'Inventario Traslados' AS TIPO,'INVF01' AS CONCEPTO,I.SUCURSAL_ID
,SUM(ROUND(I.CANTIDAD/I.FACTORU*I.COSTOP,2)) as COSTO
from sx_inventario_trd I  join sx_productos p on(p.producto_id=i.producto_id) 
where p.inventariable is true and I.FECHA BETWEEN '@FECHA_INI 00:00:00' AND '@FECHA_FIN 23:59:59' 
group by I.SUCURSAL_ID 
union
select 'Inventario Consumo Interno' AS TIPO
,(CASE 	WHEN I.TIPO_CIS='MATERIAL_EMPAQUE' THEN '151656'  
		WHEN I.TIPO_CIS='PUBLICIDAD_Y_PROPAGANDA' THEN '151688'  
		WHEN I.TIPO_CIS='NO_DEDUCIBLE' THEN '151654'  
		WHEN I.TIPO_CIS IN('PAPELERIA','PELERIA') THEN '151530'  
	ELSE 'SIN_ASIGNAR' END) AS CONCEPTO
,I.SUCURSAL_ID
,SUM(ROUND(I.CANTIDAD/I.FACTORU*I.COSTOP,2)) as COSTO
from sx_inventario_mov I  join sx_productos p on(p.producto_id=i.producto_id) 
where p.inventariable is true AND I.CONCEPTO='CIS' and I.FECHA BETWEEN '@FECHA_INI 00:00:00' AND '@FECHA_FIN 23:59:59' 
group by I.SUCURSAL_ID,
(CASE 	WHEN I.TIPO_CIS='MATERIAL_EMPAQUE' THEN '151656'  
		WHEN I.TIPO_CIS='PUBLICIDAD_Y_PROPAGANDA' THEN '151688'  
		WHEN I.TIPO_CIS='NO_DEDUCIBLE' THEN '151654'  
		WHEN I.TIPO_CIS IN('PAPELERIA','PELERIA') THEN '151530'  
	ELSE 'SIN_ASIGNAR' END)
