DROP TRIGGER ACTUALIZA_EXISTXTRD

CREATE TRIGGER ACTUALIZA_EXISTXTRD
BEFORE  insert ON sx_inventario_trd
FOR EACH ROW
BEGIN
call ACTUALIZA_EXISTXTRD(NEW.CANTIDAD,NEW.TIPO,NEW.CLAVE,NEW.SUCURSAL_ID);
 END