SELECT A.NOMBRE AS ALMACEN,D.CLAVE
 ,SUM(D.KILOS-IFNULL((SELECT SUM(O.KILOS) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(O.FECHA)<=DATE(CURRENT_DATE)),0) 
    -IFNULL((SELECT SUM(S.CANTIDAD) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=DATE(CURRENT_DATE)),0)) AS CANTIDAD,0 AS PENDIENTE,null AS MODIFICADO
FROM sx_maq_entradasdet D JOIN sx_almacenes A ON(D.ALMACEN_ID=A.ALMACEN_ID) JOIN sx_productos P ON(P.PRODUCTO_ID=D.PRODUCTO_ID) 
JOIN SX_LINEAS L ON(L.LINEA_ID=P.LINEA_ID) JOIN SX_CLASES C ON(C.CLASE_ID=P.CLASE_ID) JOIN SX_MARCAS M ON(M.MARCA_ID=P.MARCA_ID)
WHERE D.FECHA<=DATE(CURRENT_DATE) AND D.CLAVE =?
and (D.KILOS-IFNULL((SELECT SUM(O.KILOS) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(O.FECHA)<=DATE(CURRENT_DATE)),0) 
    -IFNULL((SELECT SUM(S.CANTIDAD) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=DATE(CURRENT_DATE)),0))<>0
GROUP BY A.NOMBRE,D.CLAVE
UNION
SELECT A.NOMBRE AS ALMACEN,O.DESTINO_CLAVE AS CLAVE
        ,SUM((R.ENTRADA-IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=DATE(CURRENT_DATE)),0))) AS CANTIDAD,0 AS PENDIENTE,null AS MODIFICADO
FROM sx_maq_recepcion_cortedet R 
	JOIN sx_maq_entradasdet E ON (R.ENTRADADET_ID=E.ENTRADADET_ID )
     	JOIN sx_almacenes A ON(A.ALMACEN_ID=R.ALMACEN_ID) 
	JOIN sx_maq_ordenesdet O ON(O.ORDENDET_ID=R.ORDENDET_ID) JOIN sx_productos P ON(O.PRODUCTO_DESTINO_ID=P.PRODUCTO_ID) 
WHERE DATE(R.FECHA)<=DATE(CURRENT_DATE)  AND O.DESTINO_CLAVE =? AND 
(R.ENTRADA-IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=DATE(CURRENT_DATE)),0))>0
GROUP BY A.NOMBRE,O.DESTINO_CLAVE