SELECT x.tipo,x.origen_id,x.cliente,x.docto,x.fechad,x.origen,x.suc,x.documento,x.fecha,X.linea,X.clave,X.descripcion
,ROUND(SUM(X.IMP_NETO),2) AS ventaNeta,ROUND(SUM(X.COSTO),2) AS costo
,(ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2)) AS importeUtilidad
,((ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2))*100)/ROUND(SUM(X.IMP_NETO),2) AS porcentajeUtilidad
,ROUND((X.KILOS),2) AS kilos,ROUND(SUM(X.IMP_NETO),2)/ROUND((X.KILOS),2) AS precio_kilos
,ROUND(SUM(X.COSTO)/(X.KILOS),2) AS costo_kilos
FROM (
SELECT D.TIPO,D.ORIGEN_ID,D.CLIENTE,D.DOCTO,D.FECHA AS FECHAD,D.ORIGEN,D.SUC,D.DOCTO AS DOCUMENTO,D.FECHA
,D.LINEA,D.CLAVE,D.DESCRIPCION,SUM(D.IMP_NETO) AS IMP_NETO,SUM(D.COSTO_NETO) AS COSTO,SUM(D.KILOS) AS KILOS
FROM  FACT_VENTASDET D   USE INDEX (FECHA)
WHERE D.CLAVE<>'ANTICIPO' AND D.FECHA BETWEEN '@FECHA_INI' AND '@FECHA_FIN' AND D.CLAVE='@CLAVE' @VENTA @ORIGEN_ID
GROUP BY  D.CLAVE,d.DOCTO,d.fecha,d.sucursal_id
) AS X  GROUP BY X.clave,X.documento,X.fecha,X.suc