SELECT X.linea,X.clase,X.marca,X.clave,X.descripcion,X.KXMIL AS kilosMillar,x.gramos,x.calibre,x.caras,x.deLinea,x.nacional
,ROUND(SUM(X.IMP_NETO),2) AS ventaNeta,ROUND(SUM(X.COSTO),2) AS costo
,(ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2)) AS importeUtilidad
,((ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2))*100)/ROUND(SUM(X.IMP_NETO),2) AS porcentajeUtilidad
,(CASE WHEN X.TIPO='EXI' THEN 0 ELSE SUM(X.INV_COSTO) END) AS inventarioCosteado,x.nacional
,ROUND((X.KILOS),2) AS kilos,ROUND(SUM(X.IMP_NETO),2)/ROUND((X.KILOS),2) AS precio_kilos
FROM (
SELECT 
D.TIPO,D.LINEA,D.CLAVE,D.DESCRIPCION,D.KXMIL,D.GRAMOS,D.CALIBRE,D.CARAS,(CASE WHEN D.DELINEA IS TRUE THEN 'L' ELSE 'E' END) AS DELINEA
,SUM(D.IMP_NETO) AS IMP_NETO,SUM(D.COSTO_NETO) AS COSTO,0.0 AS INV_COSTO,(CASE WHEN D.nacional IS TRUE THEN 'NAL' ELSE 'IMP' END) AS NACIONAL,SUM(D.KILOS) AS KILOS
,D.CLASE,D.MARCA
FROM  FACT_VENTASDET D   USE INDEX (FECHA)
WHERE D.CLAVE<>'ANTICIPO' @VENTA AND D.FECHA BETWEEN '@FECHA_INI' AND '@FECHA_FIN'  @ORIGEN_ID
GROUP BY  D.CLAVE
) AS X  GROUP BY X.clave