SELECT X.periodo ,X.origenId
,X.DESCRIP AS descripcion,ROUND(SUM(X.IMP_NETO),2) AS ventaNeta,ROUND(SUM(X.COSTO),2) AS costo
,(ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2)) AS importeUtilidad
,((ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2))*100)/ROUND(SUM(X.IMP_NETO),2) AS porcentajeUtilidad
,ROUND((X.KILOS),2) AS kilos,ROUND(SUM(X.IMP_NETO),2)/ROUND((X.KILOS),2) AS precio_kilos
,(CASE WHEN X.TIPO='EXI' THEN 0 ELSE SUM(X.INV_COSTO) END) AS inventarioCosteado,x.nacional
FROM (
SELECT 
'@MES - @YEAR' AS PERIODO,@DESCRIPCION AS DESCRIP
,SUM(D.IMP_NETO) AS IMP_NETO,SUM(D.COSTO_NETO) AS COSTO,0.0 AS INV_COSTO,(CASE WHEN D.nacional IS TRUE THEN 'NAL' ELSE 'IMP' END) AS NACIONAL,SUM(D.KILOS) AS KILOS
FROM  FACT_VENTASDET D  USE INDEX (FECHA)
WHERE D.CLAVE<>'ANTICIPO' AND D.FECHA BETWEEN '@FECHA_INI' AND '@FECHA_FIN' @VENTA
GROUP BY  DESCRIP,D.NACIONAL
UNION
SELECT 
'@MES - @YEAR' AS PERIODO,@INVENTARIO AS DESCRIP
,0.0 AS IMP_NETO,0.0 AS COSTO,ROUND(SUM(D.CANTIDAD/D.FACTORU*D.COSTOP),2) AS INV_COSTO,(CASE WHEN P.nacional IS TRUE THEN 'NAL' ELSE 'IMP' END) AS NACIONAL,0 AS KILOS
FROM  sx_existencias D USE INDEX (INDX_INV_EXI2) JOIN SX_PRODUCTOS P ON (P.PRODUCTO_ID=D.PRODUCTO_ID) JOIN sx_lineas L ON (L.LINEA_ID=P.LINEA_ID) 
WHERE D.YEAR=YEAR('@FECHA_INI') AND D.MES=MONTH('@FECHA_FIN')
GROUP BY  DESCRIP,P.NACIONAL
) AS X  GROUP BY X.DESCRIP,X.NACIONAL