SELECT X.periodo ,X.origenId
,X.DESCRIP AS descripcion,ROUND(SUM(X.IMP_NETO),2) AS ventaNeta,ROUND(SUM(X.COSTO),2) AS costo
,(ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2)) AS importeUtilidad
,((ROUND(SUM(X.IMP_NETO),2)-ROUND(SUM(X.COSTO),2))*100)/ROUND(SUM(X.IMP_NETO),2) AS porcentajeUtilidad
,ROUND((X.KILOS),2) AS kilos,ROUND(SUM(X.IMP_NETO)/(X.KILOS),2) AS precio_kilos
,ROUND(SUM(X.COSTO)/(X.KILOS),2) AS costo_kilos
,(CASE WHEN X.TIPO='EXI' THEN 0 ELSE SUM(X.INV_COSTO) END) AS inventarioCosteado,SUM(X.KILOS_INV) AS kilosInv
FROM (
SELECT 
'@MES - @YEAR' AS PERIODO,@DESCRIPCION AS DESCRIP
,SUM(D.IMP_NETO) AS IMP_NETO,SUM(D.COSTO_NETO) AS COSTO,0.0 AS INV_COSTO,SUM(D.KILOS) AS KILOS,0 AS KILOS_INV
FROM  FACT_VENTASDET D  USE INDEX (FECHA)
WHERE D.CLAVE<>'ANTICIPO' AND D.FECHA BETWEEN '@FECHA_INI' AND '@FECHA_FIN' @VENTA @TIPO_PROD
GROUP BY  DESCRIP
UNION
SELECT 
'@MES - @YEAR' AS PERIODO,@INVENTARIO AS DESCRIP
,0.0 AS IMP_NETO,0.0 AS COSTO,ROUND(SUM(D.CANTIDAD/D.FACTORU*D.COSTOP),2) AS INV_COSTO,0 AS KILOS,sum(D.CANTIDAD/D.FACTORU*P.KILOS) AS KILOS_INV
FROM  sx_existencias D USE INDEX (INDX_INV_EXI2) JOIN SX_PRODUCTOS P ON (P.PRODUCTO_ID=D.PRODUCTO_ID) JOIN sx_lineas L ON (L.LINEA_ID=P.LINEA_ID) 
WHERE D.YEAR=YEAR('@FECHA_INI') AND D.MES=MONTH('@FECHA_FIN') @TIPO_PROD
GROUP BY  DESCRIP
) AS X  GROUP BY X.DESCRIP