SELECT 'FICHA' AS TIPO,f.FICHA_ID AS ORIGEN_ID,B.FECHA,S.NOMBRE AS SUCURSAL,b.CARGOABONO_ID
,case when B.ORIGEN='VENTA_CAMIONETA' THEN 'CAM' WHEN B.ORIGEN='VENTA_MOSTRADOR' THEN 'MOS' ELSE 'N/D' END AS ORIGEN
,CASE WHEN F.TIPO_FICHA='EFECTIVO' THEN concat('FICHA-',F.TIPO_FICHA,' FOLIO:',CAST(F.FOLIO AS CHAR)) ELSE concat('FICHA-CHEQUE',' ',F.TIPO_FICHA,' FOLIO:',CAST(F.FOLIO AS CHAR)) END AS CONCEPTO
,B.IMPORTE,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS BANCO 
,CASE WHEN F.TIPO_FICHA='EFECTIVO' THEN 'EFECTIVO' ELSE 'CHEQUE' END DESCRIPCION  
FROM sw_bcargoabono b join sx_fichas f on(f.CARGOABONO_ID=b.CARGOABONO_ID) JOIN sw_sucursales S ON(S.SUCURSAL_ID=B.SUCURSAL_ID) where b.fecha=? and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA') 
union
SELECT 'DEPOSITO' AS TIPO,a.ABONO_ID AS ORIGEN_ID,B.FECHA,S.NOMBRE AS SUCURSAL,b.CARGOABONO_ID
,case when B.ORIGEN='VENTA_CAMIONETA' THEN 'CAM' WHEN B.ORIGEN='VENTA_MOSTRADOR' THEN 'MOS' ELSE 'N/D' END AS ORIGEN
,CASE WHEN A.TRANSFERENCIA<>0 THEN CONCAT('TRANSFERENCIA','-',(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID),' REF:',IFNULL(A.REFERENCIA,'')) ELSE CONCAT('DEPOSITO','-',(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID),' REF:',IFNULL(A.REFERENCIA,'')) END AS CONCEPTO
,B.IMPORTE-IFNULL((SELECT SUM(X.IMPORTE) FROM SX_CXC_APLICACIONES X JOIN SX_VENTAS V ON(V.CARGO_ID=X.CARGO_ID) WHERE X.ABONO_ID=A.ABONO_ID AND V.TIPO='TES'),0) AS IMPORTE
,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS BANCO 
,CASE WHEN A.TRANSFERENCIA<>0 THEN 'TRANSFERENCIA' ELSE 'DEPOSITO' END DESCRIPCION  
 FROM sw_bcargoabono b join sx_cxc_abonos a on(a.ABONO_ID=b.PAGO_ID) JOIN sw_sucursales S ON(S.SUCURSAL_ID=B.SUCURSAL_ID) where b.fecha=? and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA') and b.conciliado=false
 		AND A.ABONO_ID NOT IN(SELECT X.ABONO_ID FROM SX_CXC_APLICACIONES X JOIN SX_VENTAS V ON(V.CARGO_ID=X.CARGO_ID) WHERE X.ABONO_ID=A.ABONO_ID AND V.TIPO='TES')
union
SELECT 'TARJETA' AS TIPO,cast(c.CORTE_ID as CHAR) AS ORIGEN_ID,B.FECHA,S.NOMBRE AS SUCURSAL,b.CARGOABONO_ID
,'MOS' AS ORIGEN
,case when C.TIPO='INGRESO' THEN CONCAT('CORTE DE TARJETA:',CAST(C.CORTE_ID AS CHAR),' ',B.REFERENCIA) WHEN C.TIPO='IMPUESTO' THEN CONCAT(C.TIPO,' CORTE:',CAST(C.CORTE_ID AS CHAR),' ',B.REFERENCIA)  ELSE CONCAT(C.TIPO,' CORTE:',CAST(C.CORTE_ID AS CHAR))  END AS CONCEPTO
,B.IMPORTE,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS BANCO,B.REFERENCIA AS DESCRIPCION 
FROM sw_bcargoabono b join sx_corte_tarjetas_aplicaciones c on(c.CARGOABONO_ID=b.CARGOABONO_ID) JOIN sw_sucursales S ON(S.SUCURSAL_ID=B.SUCURSAL_ID)
where b.fecha=? and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA','VENTA_CREDITO') 