select V.TIPO,S.NOMBRE AS SUCURSAL,V.CARGO_ID,V.ORIGEN,V.TOTAL,V.IMPORTE,V.IMPUESTO from SX_VENTAS V JOIN SW_SUCURSALES S ON(S.SUCURSAL_ID=V.SUCURSAL_ID) WHERE V.FECHA='2011/05/31' AND V.TIPO='FAC'


---FICHAS
SELECT f.FICHA_ID,B.FECHA,B.SUCURSAL_ID,b.CARGOABONO_ID,B.ORIGEN,B.COMENTARIO AS CONCEPTO,B.IMPORTE  
				,(SELECT X.CUENTACONTABLE FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS CUENTACONTABLE 
				,CASE WHEN F.TIPO_FICHA='EFECTIVO' THEN 'EFECTIVO' ELSE 'CHEQUE' END DESCRIPCION  
				FROM sw_bcargoabono b join sx_fichas f on(f.CARGOABONO_ID=b.CARGOABONO_ID)  
				where b.fecha='2011/05/31' b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA') --AND B.SUCURSAL_ID=?


---TRANSFERENCIA
SELECT a.ABONO_ID,B.FECHA,B.SUCURSAL_ID,b.CARGOABONO_ID,B.ORIGEN,B.COMENTARIO AS CONCEPTO,B.IMPORTE  
				,(SELECT X.CUENTACONTABLE FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS CUENTACONTABLE 
				,CASE WHEN A.TRANSFERENCIA<>0 THEN 'TRANSFERENCIA' ELSE 'DEPOSITO' END DESCRIPCION  
				 FROM sw_bcargoabono b join sx_cxc_abonos a on(a.ABONO_ID=b.PAGO_ID)  
				 where b.fecha='2011/05/31' and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA')  --AND B.SUCURSAL_ID=?


--TARJETA
SELECT c.CORTE_ID,B.FECHA,B.SUCURSAL_ID,b.CARGOABONO_ID,B.ORIGEN,B.COMENTARIO AS CONCEPTO,B.IMPORTE  
				 ,(SELECT X.CUENTACONTABLE FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS CUENTACONTABLE,B.REFERENCIA AS DESCRIPCION 
				 FROM sw_bcargoabono b join sx_corte_tarjetas_aplicaciones c on(c.CARGOABONO_ID=b.CARGOABONO_ID) 
				 where b.fecha='2011/05/31' and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA','VENTA_CREDITO') --AND B.SUCURSAL_ID=?

