select 'VENTAS' AS TIPO,V.SUCURSAL_ID,V.ORIGEN,0 AS CUENTA_ID,'' AS DESCRIPCION,'' AS REFERENCIA,'' AS REFERENCIA2,sum(V.TOTAL) AS TOTAL,sum(V.IMPORTE) as IMPORTE,sum(V.IMPUESTO) AS IMPUESTO
from SX_VENTAS V WHERE V.FECHA='2011/05/31' AND V.TIPO='FAC'  GROUP BY V.ORIGEN,V.SUCURSAL_ID


----TESORERIA / BANCOS ----------------

---FICHAS
SELECT 'FICHAS' AS TIPO,B.SUCURSAL_ID,B.ORIGEN,B.CUENTA_ID
,CASE WHEN F.TIPO_FICHA='EFECTIVO' THEN 'EFECTIVO' ELSE 'CHEQUE' END AS DESCRIPCION  
,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS REFERENCIA,'' AS REFERENCIA2
,SUM(B.IMPORTE) AS TOTAL,0 AS IMPORTE,0 AS IMPUESTO 
FROM sw_bcargoabono b join sx_fichas f on(f.CARGOABONO_ID=b.CARGOABONO_ID)  
where b.fecha='2011/05/31' AND b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA') 
GROUP BY B.SUCURSAL_ID,B.ORIGEN,CASE WHEN F.TIPO_FICHA='EFECTIVO' THEN 'EFECTIVO' ELSE 'CHEQUE' END
UNION
---TRANSFERENCIA
SELECT 'DEPOSITO' AS TIPO,B.SUCURSAL_ID,B.ORIGEN,B.CUENTA_ID
,CASE WHEN A.TRANSFERENCIA<>0 THEN 'TRANSFERENCIA' ELSE 'DEPOSITO' END DESCRIPCION  
,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS REFERENCIA,'' AS REFERENCIA2
,SUM(B.IMPORTE) AS TOTAL,0 AS IMPORTE,0 AS IMPUESTO 
FROM sw_bcargoabono b join sx_cxc_abonos a on(a.ABONO_ID=b.PAGO_ID)  
where b.fecha='2011/05/31' and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA')  --AND B.SUCURSAL_ID=?
GROUP BY B.SUCURSAL_ID,B.ORIGEN,CASE WHEN A.TRANSFERENCIA<>0 THEN 'TRANSFERENCIA' ELSE 'DEPOSITO' END
UNION
--TARJETA
SELECT 'TARJETAS' AS TIPO,B.SUCURSAL_ID,B.ORIGEN,B.CUENTA_ID
,CONCAT(B.COMENTARIO,' ',B.REFERENCIA) AS DESCRIPCION
,(SELECT X.DESCRIPCION FROM sw_cuentas X  WHERE X.id=B.CUENTA_ID) AS REFERENCIA,'' AS REFERENCIA2
,SUM(B.IMPORTE) AS TOTAL,0 AS IMPORTE,0 AS IMPUESTO 
FROM sw_bcargoabono b join sx_corte_tarjetas_aplicaciones c on(c.CARGOABONO_ID=b.CARGOABONO_ID) 
where b.fecha='2011/05/31' and b.ORIGEN IN('VENTA_MOSTRADOR','VENTA_CAMIONETA','VENTA_CREDITO')   
GROUP BY B.SUCURSAL_ID,B.ORIGEN,CONCAT(B.COMENTARIO,' ',B.REFERENCIA)
