package com.luxsoft.siipap.pos;

public enum POSRoles {
	
	GERENTE_DE_VENTAS
	,ADMINISTRADOR_DE_VENTAS
	,ADMINISTRADOR_DE_COMRAS
	,CAJERO
	,VENDEDOR
	,FACTURISTA
	,EMBARQUES
	,AUTORIZADOR_DE_DEPOSITOS
	,FACTURACION_ESPECIAL
	,ADMINISTRACION_INVENTARIOS
	,GERENTE_DE_INVENTARIOS
	,ADMINISTRACION_EMBARQUES
	,NOTAS_POR_DEVOLUCION
	,CONTROLADOR_DE_INVENTARIOS
	,CONTROLADOR_DE_ANTICIPOS
	,CONTROLADOR_DE_COMPRAS
	

}
