SELECT 'MQ' AS TIPO,year(CURRENT_DATE) AS YEAR,MONTH(CURRENT_DATE) AS MES,D.CLAVE,D.DESCRIPCION,P.UNIDAD,L.NOMBRE as LINEA,M.NOMBRE as MARCA,C.NOMBRE as CLASE
 ,SUM(D.KILOS-IFNULL((SELECT SUM(O.KILOS) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(O.FECHA)<=DATE(CURRENT_DATE)),0) 
    -IFNULL((SELECT SUM(S.CANTIDAD) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=DATE(CURRENT_DATE)),0)) AS CANTIDAD,0 AS RECORTE
FROM sx_maq_entradasdet D JOIN sx_almacenes A ON(D.ALMACEN_ID=A.ALMACEN_ID) JOIN sx_productos P ON(P.PRODUCTO_ID=D.PRODUCTO_ID) 
JOIN SX_LINEAS L ON(L.LINEA_ID=P.LINEA_ID) JOIN SX_CLASES C ON(C.CLASE_ID=P.CLASE_ID) JOIN SX_MARCAS M ON(M.MARCA_ID=P.MARCA_ID)
WHERE D.FECHA<=DATE(CURRENT_DATE) AND D.ALMACEN_ID like '%' and p.activo is true
and (D.KILOS-IFNULL((SELECT SUM(O.KILOS) FROM sx_maq_recepcion_cortedet O WHERE O.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(O.FECHA)<=DATE(CURRENT_DATE)),0) 
    -IFNULL((SELECT SUM(S.CANTIDAD) FROM sx_maq_salida_bobinas S WHERE S.ENTRADADET_ID=D.ENTRADADET_ID  AND DATE(S.FECHA)<=DATE(CURRENT_DATE)),0))<>0
GROUP BY D.CLAVE,D.DESCRIPCION,P.UNIDAD,L.NOMBRE,M.NOMBRE,C.NOMBRE
UNION
SELECT 'MQ' AS TIPO,year(CURRENT_DATE) AS YEAR,MONTH(CURRENT_DATE) AS MES,O.DESTINO_CLAVE AS CLAVE,O.DESTINO_DESCRIPCION AS DESCRIPCION,P.UNIDAD,L.NOMBRE as LINEA,M.NOMBRE as MARCA,C.NOMBRE as CLASE
        ,SUM((R.ENTRADA-IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=DATE(CURRENT_DATE)),0))) AS CANTIDAD,0 AS RECORTE
FROM sx_maq_recepcion_cortedet R 
	JOIN sx_maq_entradasdet E ON (R.ENTRADADET_ID=E.ENTRADADET_ID )
     	JOIN sx_almacenes A ON(A.ALMACEN_ID=R.ALMACEN_ID) 
	JOIN sx_maq_ordenesdet O ON(O.ORDENDET_ID=R.ORDENDET_ID) JOIN sx_productos P ON(O.PRODUCTO_DESTINO_ID=P.PRODUCTO_ID) 
JOIN SX_LINEAS L ON(L.LINEA_ID=P.LINEA_ID) JOIN SX_CLASES C ON(C.CLASE_ID=P.CLASE_ID) JOIN SX_MARCAS M ON(M.MARCA_ID=P.MARCA_ID)
WHERE DATE(R.FECHA)<=DATE(CURRENT_DATE) AND A.ALMACEN_ID LIKE '%' and p.activo is true AND 
(R.ENTRADA-IFNULL((SELECT SUM(CANTIDAD) FROM sx_maq_salida_hojeadodet H WHERE H.RECEPCIONDET_ID=R.RECEPCIONDET_ID AND DATE(H.FECHA)<=DATE(CURRENT_DATE)),0))>0
GROUP BY O.DESTINO_CLAVE,O.DESTINO_DESCRIPCION,P.UNIDAD,L.NOMBRE,M.NOMBRE,C.NOMBRE