SELECT A.CLAVE, P.DESCRIPCION,l.NOMBRE AS LINEA,c.NOMBRE AS CLASE,m.nombre as marca
,SUM(CASE WHEN A.TIPO='INI' THEN A.CANTIDAD ELSE 0 END) AS saldoInicial
,SUM(CASE WHEN A.TIPO='INI' THEN A.COSTO ELSE 0 END) AS costoIni
,SUM(CASE WHEN A.TIPO='SNA' THEN A.CANTIDAD ELSE 0 END) AS comsSinAUni
,SUM(CASE WHEN A.TIPO='SNA' THEN A.COSTO ELSE 0 END) AS comsSinA
,SUM(CASE WHEN A.TIPO='COM' THEN A.CANTIDAD ELSE 0 END) AS comsUni
,SUM(CASE WHEN A.TIPO='COM' THEN A.COSTO ELSE 0 END) AS comsCosto
,SUM(CASE WHEN A.TIPO='MAQ' THEN A.CANTIDAD ELSE 0 END) AS maqUni
,SUM(CASE WHEN A.TIPO='MAQ' THEN A.COSTO ELSE 0 END) AS maqCosto
,SUM(CASE WHEN A.TIPO='SRV' THEN A.COSTO ELSE 0 END) AS servicioCosto
,SUM(CASE WHEN A.TIPO='MVS' THEN A.CANTIDAD ELSE 0 END) AS movsUni
,SUM(CASE WHEN A.TIPO='MVS' THEN A.COSTO ELSE 0 END) AS movsCosto
,SUM(CASE WHEN A.TIPO='DEC' THEN A.CANTIDAD ELSE 0 END) AS decUni
,SUM(CASE WHEN A.TIPO='DEC' THEN A.COSTO ELSE 0 END) AS decCosto
,SUM(CASE WHEN A.TIPO='TRD' THEN A.CANTIDAD ELSE 0 END) AS trasladosUni
,SUM(CASE WHEN A.TIPO='TRD' THEN A.COSTO ELSE 0 END) AS trasladosCosto
,SUM(CASE WHEN A.TIPO='TRS' THEN A.CANTIDAD ELSE 0 END) AS trsSalUni
,SUM(CASE WHEN A.TIPO='TRS' THEN A.COSTO ELSE 0 END) AS trsSalCosto
,SUM(CASE WHEN A.TIPO='TRE' THEN A.CANTIDAD ELSE 0 END) AS trsEntUni
,SUM(CASE WHEN A.TIPO='TRE' THEN A.COSTO ELSE 0 END) AS trsEntCosto
,SUM(CASE WHEN A.TIPO='DEV' THEN A.CANTIDAD ELSE 0 END) AS devUni
,SUM(CASE WHEN A.TIPO='DEV' THEN A.COSTO ELSE 0 END) AS devCosto
,SUM(CASE WHEN A.TIPO='FAC' THEN A.CANTIDAD ELSE 0 END) AS vtaUni
,SUM(CASE WHEN A.TIPO='FAC' THEN A.COSTO ELSE 0 END) AS vtaCosto
,SUM(CASE WHEN A.TIPO='SLD' THEN A.CANTIDAD ELSE 0 END) AS SALDO
,SUM(CASE WHEN A.TIPO='SLD' THEN A.COSTO ELSE 0 END) AS COSTO
,IFNULL(X.COSTOP,0) AS COSTOP
FROM (
SELECT 'INI' AS TIPO,E.CLAVE,SUM(E.CANTIDAD/E.FACTORU) as CANTIDAD,SUM(E.CANTIDAD/E.FACTORU*E.COSTOP) AS COSTO FROM sx_existencias E WHERE YEAR(E.FECHA)=@INI_YEAR AND MONTH(E.FECHA)=@INI_MES GROUP BY E.CLAVE
UNION
select 'SNA' AS TIPO,I.CLAVE,sum((I.CANTIDAD/I.FACTORU)) AS CANTIDAD,sum((I.CANTIDAD/I.FACTORU)*I.COSTOP) AS COSTO from sx_inventario_com I LEFT JOIN SX_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where I.FECHA between '@FECHA_INI' and '@FECHA_FIN' AND X.ENTRADA_ID IS NULL GROUP BY I.CLAVE
UNION
select 'COM' AS TIPO,I.CLAVE ,sum((X.CANTIDAD/I.FACTORU)) AS CANTIDAD,sum((X.COSTOMN*X.CANTIDAD/I.FACTORU)) AS COSTO from sx_inventario_com I JOIN V_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where I.FECHA between '@FECHA_INI' and '@FECHA_FIN'  GROUP BY I.CLAVE 
UNION
SELECT 'MAQ' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.COSTO) AS COSTO FROM sx_inventario_maq I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'SRV' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.GASTOS) AS COSTO FROM sx_inventario_trs I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'MVS' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.costop) AS COSTO FROM sx_inventario_mov I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'DEC' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD ,SUM(I.CANTIDAD/I.FACTORU*I.costop) AS COSTO FROM sx_inventario_dec I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'TRD' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.costop) AS COSTO FROM sx_inventario_trd I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'TRS' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) AS COSTO FROM sx_inventario_trs I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' AND I.CANTIDAD<0 GROUP BY I.CLAVE
UNION
SELECT 'TRE' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.COSTOORIGEN) AS COSTO FROM sx_inventario_trs I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN'  AND I.CANTIDAD>0 GROUP BY I.CLAVE
UNION
SELECT 'DEV' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) AS COSTO FROM sx_inventario_dev I WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'FAC' AS TIPO,I.CLAVE,SUM(I.CANTIDAD/I.FACTORU) AS CANTIDAD,SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) AS COSTO FROM sx_ventasdet I  USE INDEX (INDX_VDET2) WHERE I.FECHA between '@FECHA_INI' and '@FECHA_FIN' GROUP BY I.CLAVE
UNION
SELECT 'SLD' AS TIPO,E.CLAVE,SUM(E.CANTIDAD/E.FACTORU) AS CANTIDAD,SUM(E.CANTIDAD/E.FACTORU*E.COSTOP) AS COSTO FROM sx_existencias E WHERE YEAR(E.FECHA)=@YEAR AND MONTH(E.FECHA)=@MES GROUP BY E.CLAVE
) AS A
JOIN  sx_productos P ON(A.CLAVE=P.CLAVE) left join SX_LINEAS l on (p.linea_id=l.linea_id) left join sx_clases c on(p.clase_id=c.clase_id) left join sx_marcas m on (p.marca_id=m.marca_id)
LEFT join sx_costos_p x on(x.clave=p.clave and  YEAR=@YEAR AND MES=@MES)
where p.inventariable=true
GROUP BY A.CLAVE, P.DESCRIPCION,l.NOMBRE,c.NOMBRE,m.nombre,X.COSTOP