select 'A_INV_INI' AS GRUPO,'INI' AS TIPO,I.CLAVE,I.FECHA,1 AS DOCTO,1 AS RENGL,S.NOMBRE,P.UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTO AS IMPORTECOSTO
,YEAR(I.FECHA) AS YEAR,month(I.FECHA) AS MES,' ' AS COMENTARIO from sx_existencias I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID) JOIN sx_PRODUCTOS P ON(P.CLAVE=I.CLAVE) where YEAR=@INI_YEAR AND MES=@INI_MES AND I.CLAVE=@CLAVE
union
select 'COMPRAS' AS GRUPOX,'SNA' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_com I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  LEFT JOIN SX_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE =@CLAVE AND X.ENTRADA_ID IS NULL
union
select 'COMPRAS' AS GRUPOX,'COM' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,X.COSTOMN AS COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*X.COSTOMN AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_com I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  JOIN v_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE =@CLAVE
union
select 'COMPRAS' AS GRUPO,I.MAQUILA_TIPO AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTO AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_maq I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE
union
select 'VENTAS' AS GRUPO,'FAC' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_ventasdet I  use index(INDX_VDET2) JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where I.FECHA between '@FECHA_INI' and '@FECHA_FIN' AND I.CLAVE=@CLAVE
union
select 'VENTAS' AS GRUPO,'DEV' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_dev I  JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE
union
select 'MOVIMIENTOS' AS GRUPO,I.CONCEPTO AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_mov I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE
union
select 'DEV_PROV' AS GRUPO,'DEC' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_dec I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE
union
SELECT 'TRANSFORMACION' AS GRUPO,TRTIP AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTOP AS COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO  FROM sx_inventario_trs I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=@CLAVE AND I.CANTIDAD<0 
union
SELECT 'TRANSFORMACION' AS GRUPO,TRTIP AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTO AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO  FROM sx_inventario_trs I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=@CLAVE AND I.CANTIDAD>0 
union
select 'TRASLADO' AS GRUPO,CASE WHEN I.CANTIDAD<0 THEN 'TPS' ELSE 'TPE' END AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS
,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_trd I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE
union
select 'TRANSFORMACION' AS GRUPO,'KIT' AS TIPO,I.CLAVE,I.FECHA,I.DOCUMENTO,I.RENGLON,S.NOMBRE,I.UNIDAD_ID AS UNIDAD,I.CANTIDAD,I.KILOS,I.COSTO,I.COSTOP,I.CANTIDAD/I.FACTORU*I.COSTOP AS IMPORTECOSTO
,year(I.FECHA) AS YEAR,month(I.FECHA) AS MES,I.COMENTARIO from sx_inventario_kit I JOIN sw_sucursales S ON(S.SUCURSAL_ID=I.SUCURSAL_ID)  where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES AND I.CLAVE=@CLAVE