SELECT P.CLAVE,P.DESCRIPCION,X.NOMBRE AS LINEA,Y.NOMBRE AS CLASE,z.nombre as marca
,IFNULL((SELECT SUM(E.CANTIDAD/E.FACTORU) FROM sx_existencias E WHERE YEAR(E.FECHA)=@INI_YEAR AND MONTH(E.FECHA)=@INI_MES  AND E.CLAVE=P.CLAVE GROUP BY E.CLAVE),0) AS saldoInicial
,IFNULL((SELECT SUM(E.CANTIDAD/E.FACTORU*E.COSTOP) FROM sx_existencias E WHERE YEAR(E.FECHA)=@INI_YEAR AND MONTH(E.FECHA)=@INI_MES  AND E.CLAVE=P.CLAVE GROUP BY E.CLAVE),0) AS costoIni
,IFNULL(((select sum((I.CANTIDAD/I.FACTORU)*I.COSTOP) from sx_inventario_com I LEFT JOIN SX_CXP_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE =P.CLAVE AND X.ENTRADA_ID IS NULL )),0) AS comsSinA
,IFNULL(((select sum((X.CANTIDAD/I.FACTORU)) from sx_inventario_com I JOIN SX_CXP_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE =P.CLAVE)),0) AS comsUni
,IFNULL(((select sum((X.COSTOMN*X.CANTIDAD/I.FACTORU)) from sx_inventario_com I JOIN v_analisisdet X ON(I.INVENTARIO_ID=X.ENTRADA_ID) where YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE =P.CLAVE)),0) AS comsCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU) FROM sx_inventario_maq I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS maqUni
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.COSTO) FROM sx_inventario_maq I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS maqCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.GASTOS) FROM sx_inventario_trs I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS servicioCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.costop) FROM sx_inventario_mov I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS movsCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.costop) FROM sx_inventario_dec I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS decCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.costop) FROM sx_inventario_trd I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS trasladosCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) FROM sx_inventario_trs I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE AND I.CANTIDAD<0 GROUP BY I.CLAVE),0) AS trsSalCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU) FROM sx_inventario_trs I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE AND I.CANTIDAD>0 GROUP BY I.CLAVE),0) AS trsEntUni
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.COSTOORIGEN) FROM sx_inventario_trs I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE AND I.CANTIDAD>0 GROUP BY I.CLAVE),0) AS trsEntCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) FROM sx_inventario_dev I WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS devCosto
,IFNULL((SELECT SUM(I.CANTIDAD/I.FACTORU*I.COSTOP) FROM sx_ventasdet I  USE INDEX (INDX_VDET2) WHERE YEAR(I.FECHA)=@YEAR AND MONTH(I.FECHA)=@MES  AND I.CLAVE=P.CLAVE GROUP BY I.CLAVE),0) AS vtaCosto
,IFNULL((SELECT SUM(E.CANTIDAD/E.FACTORU) FROM sx_existencias E WHERE YEAR(E.FECHA)=@YEAR AND MONTH(E.FECHA)=@MES  AND E.CLAVE=P.CLAVE GROUP BY E.CLAVE),0) AS SALDO
,IFNULL((SELECT SUM(E.CANTIDAD/E.FACTORU*E.COSTOP) FROM sx_existencias E WHERE YEAR(E.FECHA)=@YEAR AND MONTH(E.FECHA)=@MES  AND E.CLAVE=P.CLAVE GROUP BY E.CLAVE),0) AS COSTO
,IFNULL((SELECT I.COSTOP FROM sx_costos_p I WHERE YEAR=@YEAR AND MES=@MES  AND I.CLAVE=P.CLAVE ),0) AS COSTOP
FROM sx_productos P left join SX_LINEAS x on (p.linea_id=x.linea_id) left join sx_clases y on(p.clase_id=y.clase_id) left join sx_marcas z on (p.marca_id=z.marca_id)
where p.inventariable=true