SELECT EXTRACT (YEAR FROM A.F_DOCTO) AS Year,EXTRACT (MONTH FROM A.F_DOCTO) AS Mes,SUM(
    A.IMPORTE+((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100) ) AS total
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=1 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100) ELSE 0 END) ene
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=2 THEN 
    A.IMPORTE+((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) feb
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=3 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) mar
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=4 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) abr
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=5 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) may
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=6 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) jun
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=7 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) jul
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=8 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) ago
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=9 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) sep
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=10 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) oct
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=11 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) nov
,SUM(CASE WHEN EXTRACT (MONTH FROM A.F_DOCTO)=12 THEN 
    A.IMPORTE +((A.IMPORTE*100 / (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') AND X.SUCURSAL IS NOT NULL AND  EXTRACT (MONTH FROM X.F_DOCTO)=1))*
    (SELECT SUM(X.IMPORTE) FROM ANALISIS_GASTOS X WHERE  X.INVERSION = 0 AND  EXTRACT(YEAR FROM X.F_DOCTO)=@YEAR AND X.F_DOCTO IS NOT NULL AND X.SUCURSAL IN('TRANSITO','VENTAS','OFICINAS') AND  EXTRACT (MONTH FROM X.F_DOCTO)=1)/100)  ELSE 0 END) dic
FROM ANALISIS_GASTOS A 
WHERE EXTRACT(YEAR FROM A.F_DOCTO)=@YEAR
  AND A.F_DOCTO IS NOT NULL 
  AND A.SUCURSAL LIKE '%'
  AND A.SUCURSAL NOT IN('TRANSITO','VENTAS','OFICINAS') 
  AND A.SUCURSAL IS NOT NULL
  AND A.INVERSION = 0
GROUP BY EXTRACT (YEAR FROM A.F_DOCTO),EXTRACT (MONTH FROM A.F_DOCTO)