select year,mes,SUM((cantidad+DEVOLUCIONES)*COSTO) as total 
,SUM(CASE WHEN MES=1 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS ene
,SUM(CASE WHEN MES=2 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS feb
,SUM(CASE WHEN MES=3 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS mar
,SUM(CASE WHEN MES=4 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS abr
,SUM(CASE WHEN MES=5 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS may
,SUM(CASE WHEN MES=6 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS jun
,SUM(CASE WHEN MES=7 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS jul
,SUM(CASE WHEN MES=8 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS ago
,SUM(CASE WHEN MES=9 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS sep
,SUM(CASE WHEN MES=10 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS oct
,SUM(CASE WHEN MES=11 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS nov
,SUM(CASE WHEN MES=12 THEN (cantidad+DEVOLUCIONES)*COSTO ELSE 0 END) AS dic
from ventasdet_2008 where year=? @ORIGEN
group by year,mes 