SELECT EXTRACT(YEAR FROM FECHADOCUMENTO) AS Year
,EXTRACT(MONTH FROM FECHADOCUMENTO) AS Mes
,SUM(ROUND(IMPORTE/1.15,2)) AS total 
,SUM(CASE WHEN MES=1 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS ene
,SUM(CASE WHEN MES=2 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS feb
,SUM(CASE WHEN MES=3 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS mar
,SUM(CASE WHEN MES=4 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS abr
,SUM(CASE WHEN MES=5 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS may
,SUM(CASE WHEN MES=6 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS jun
,SUM(CASE WHEN MES=7 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS jul
,SUM(CASE WHEN MES=8 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS ago
,SUM(CASE WHEN MES=9 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS sep
,SUM(CASE WHEN MES=10 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS oct
,SUM(CASE WHEN MES=11 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS nov
,SUM(CASE WHEN MES=12 THEN ROUND(IMPORTE/1.15,2) ELSE 0 END) AS dic
FROM SW_NOTASDET 
WHERE YEAR=? AND TIPO IN(@TIPOS)
@ORIGEN
GROUP BY EXTRACT(YEAR FROM FECHADOCUMENTO)
,EXTRACT(MONTH FROM FECHADOCUMENTO)